/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPacksRouteImport } from './routes/admin/packs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInviteRouteImport } from './routes/admin/invite'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacksRoute = AdminPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/packs': typeof PacksRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/redeem': typeof RedeemRoute
  '/reels': typeof ReelsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tourism': typeof TourismRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/packs': typeof PacksRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/redeem': typeof RedeemRoute
  '/reels': typeof ReelsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tourism': typeof TourismRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/packs': typeof PacksRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/redeem': typeof RedeemRoute
  '/reels': typeof ReelsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tourism': typeof TourismRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artists'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/packs'
    | '/partners'
    | '/program'
    | '/redeem'
    | '/reels'
    | '/testimonials'
    | '/tourism'
    | '/admin/bookings'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/packs'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/packs'
    | '/partners'
    | '/program'
    | '/redeem'
    | '/reels'
    | '/testimonials'
    | '/tourism'
    | '/admin/bookings'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/packs'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artists'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/packs'
    | '/partners'
    | '/program'
    | '/redeem'
    | '/reels'
    | '/testimonials'
    | '/tourism'
    | '/admin/bookings'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/packs'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRoute
  CompetitionRoute: typeof CompetitionRoute
  GalleryRoute: typeof GalleryRoute
  HotelRoute: typeof HotelRoute
  PacksRoute: typeof PacksRoute
  PartnersRoute: typeof PartnersRoute
  ProgramRoute: typeof ProgramRoute
  RedeemRoute: typeof RedeemRoute
  ReelsRoute: typeof ReelsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TourismRoute: typeof TourismRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packs': {
      id: '/admin/packs'
      path: '/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AdminPacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPacksRoute: typeof AdminPacksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPacksRoute: AdminPacksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRoute,
  CompetitionRoute: CompetitionRoute,
  GalleryRoute: GalleryRoute,
  HotelRoute: HotelRoute,
  PacksRoute: PacksRoute,
  PartnersRoute: PartnersRoute,
  ProgramRoute: ProgramRoute,
  RedeemRoute: RedeemRoute,
  ReelsRoute: ReelsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TourismRoute: TourismRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
