/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as BookTransferRouteImport } from './routes/book-transfer'
import { Route as BookTourismRouteImport } from './routes/book-tourism'
import { Route as BookRouteImport } from './routes/book'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTourismRouteImport } from './routes/admin/tourism'
import { Route as AdminShuttleRouteImport } from './routes/admin/shuttle'
import { Route as AdminPacksRouteImport } from './routes/admin/packs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInviteRouteImport } from './routes/admin/invite'
import { Route as AdminHotelRouteImport } from './routes/admin/hotel'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminCollaboratorsRouteImport } from './routes/admin/collaborators'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminBraceletsRouteImport } from './routes/admin/bracelets'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTransferRoute = BookTransferRouteImport.update({
  id: '/book-transfer',
  path: '/book-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTourismRoute = BookTourismRouteImport.update({
  id: '/book-tourism',
  path: '/book-tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTourismRoute = AdminTourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShuttleRoute = AdminShuttleRouteImport.update({
  id: '/shuttle',
  path: '/shuttle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacksRoute = AdminPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelRoute = AdminHotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollaboratorsRoute = AdminCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBraceletsRoute = AdminBraceletsRouteImport.update({
  id: '/bracelets',
  path: '/bracelets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/book': typeof BookRoute
  '/book-tourism': typeof BookTourismRoute
  '/book-transfer': typeof BookTransferRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/packs': typeof PacksRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/redeem': typeof RedeemRoute
  '/reels': typeof ReelsRoute
  '/testimonials': typeof TestimonialsRoute
  '/ticket': typeof TicketRoute
  '/tourism': typeof TourismRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bracelets': typeof AdminBraceletsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/hotel': typeof AdminHotelRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/shuttle': typeof AdminShuttleRoute
  '/admin/tourism': typeof AdminTourismRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/book': typeof BookRoute
  '/book-tourism': typeof BookTourismRoute
  '/book-transfer': typeof BookTransferRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/packs': typeof PacksRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/redeem': typeof RedeemRoute
  '/reels': typeof ReelsRoute
  '/testimonials': typeof TestimonialsRoute
  '/ticket': typeof TicketRoute
  '/tourism': typeof TourismRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bracelets': typeof AdminBraceletsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/hotel': typeof AdminHotelRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/shuttle': typeof AdminShuttleRoute
  '/admin/tourism': typeof AdminTourismRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/book': typeof BookRoute
  '/book-tourism': typeof BookTourismRoute
  '/book-transfer': typeof BookTransferRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/packs': typeof PacksRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/redeem': typeof RedeemRoute
  '/reels': typeof ReelsRoute
  '/testimonials': typeof TestimonialsRoute
  '/ticket': typeof TicketRoute
  '/tourism': typeof TourismRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bracelets': typeof AdminBraceletsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/hotel': typeof AdminHotelRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/shuttle': typeof AdminShuttleRoute
  '/admin/tourism': typeof AdminTourismRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artists'
    | '/book'
    | '/book-tourism'
    | '/book-transfer'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/packs'
    | '/partner'
    | '/partners'
    | '/program'
    | '/redeem'
    | '/reels'
    | '/testimonials'
    | '/ticket'
    | '/tourism'
    | '/admin/bookings'
    | '/admin/bracelets'
    | '/admin/clients'
    | '/admin/collaborators'
    | '/admin/discounts'
    | '/admin/hotel'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/packs'
    | '/admin/shuttle'
    | '/admin/tourism'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/book'
    | '/book-tourism'
    | '/book-transfer'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/packs'
    | '/partner'
    | '/partners'
    | '/program'
    | '/redeem'
    | '/reels'
    | '/testimonials'
    | '/ticket'
    | '/tourism'
    | '/admin/bookings'
    | '/admin/bracelets'
    | '/admin/clients'
    | '/admin/collaborators'
    | '/admin/discounts'
    | '/admin/hotel'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/packs'
    | '/admin/shuttle'
    | '/admin/tourism'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artists'
    | '/book'
    | '/book-tourism'
    | '/book-transfer'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/packs'
    | '/partner'
    | '/partners'
    | '/program'
    | '/redeem'
    | '/reels'
    | '/testimonials'
    | '/ticket'
    | '/tourism'
    | '/admin/bookings'
    | '/admin/bracelets'
    | '/admin/clients'
    | '/admin/collaborators'
    | '/admin/discounts'
    | '/admin/hotel'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/packs'
    | '/admin/shuttle'
    | '/admin/tourism'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRoute
  BookRoute: typeof BookRoute
  BookTourismRoute: typeof BookTourismRoute
  BookTransferRoute: typeof BookTransferRoute
  CompetitionRoute: typeof CompetitionRoute
  GalleryRoute: typeof GalleryRoute
  HotelRoute: typeof HotelRoute
  PacksRoute: typeof PacksRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  ProgramRoute: typeof ProgramRoute
  RedeemRoute: typeof RedeemRoute
  ReelsRoute: typeof ReelsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TicketRoute: typeof TicketRoute
  TourismRoute: typeof TourismRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-transfer': {
      id: '/book-transfer'
      path: '/book-transfer'
      fullPath: '/book-transfer'
      preLoaderRoute: typeof BookTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-tourism': {
      id: '/book-tourism'
      path: '/book-tourism'
      fullPath: '/book-tourism'
      preLoaderRoute: typeof BookTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tourism': {
      id: '/admin/tourism'
      path: '/tourism'
      fullPath: '/admin/tourism'
      preLoaderRoute: typeof AdminTourismRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shuttle': {
      id: '/admin/shuttle'
      path: '/shuttle'
      fullPath: '/admin/shuttle'
      preLoaderRoute: typeof AdminShuttleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packs': {
      id: '/admin/packs'
      path: '/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AdminPacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotel': {
      id: '/admin/hotel'
      path: '/hotel'
      fullPath: '/admin/hotel'
      preLoaderRoute: typeof AdminHotelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collaborators': {
      id: '/admin/collaborators'
      path: '/collaborators'
      fullPath: '/admin/collaborators'
      preLoaderRoute: typeof AdminCollaboratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bracelets': {
      id: '/admin/bracelets'
      path: '/bracelets'
      fullPath: '/admin/bracelets'
      preLoaderRoute: typeof AdminBraceletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBraceletsRoute: typeof AdminBraceletsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCollaboratorsRoute: typeof AdminCollaboratorsRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminHotelRoute: typeof AdminHotelRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPacksRoute: typeof AdminPacksRoute
  AdminShuttleRoute: typeof AdminShuttleRoute
  AdminTourismRoute: typeof AdminTourismRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBraceletsRoute: AdminBraceletsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCollaboratorsRoute: AdminCollaboratorsRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminHotelRoute: AdminHotelRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPacksRoute: AdminPacksRoute,
  AdminShuttleRoute: AdminShuttleRoute,
  AdminTourismRoute: AdminTourismRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRoute,
  BookRoute: BookRoute,
  BookTourismRoute: BookTourismRoute,
  BookTransferRoute: BookTransferRoute,
  CompetitionRoute: CompetitionRoute,
  GalleryRoute: GalleryRoute,
  HotelRoute: HotelRoute,
  PacksRoute: PacksRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  ProgramRoute: ProgramRoute,
  RedeemRoute: RedeemRoute,
  ReelsRoute: ReelsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TicketRoute: TicketRoute,
  TourismRoute: TourismRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
