/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as IndexRouteImport } from './routes/index'

const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/testimonials': typeof TestimonialsRoute
  '/tourism': typeof TourismRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/testimonials': typeof TestimonialsRoute
  '/tourism': typeof TourismRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/competition': typeof CompetitionRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/testimonials': typeof TestimonialsRoute
  '/tourism': typeof TourismRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/partners'
    | '/program'
    | '/testimonials'
    | '/tourism'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/partners'
    | '/program'
    | '/testimonials'
    | '/tourism'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/competition'
    | '/gallery'
    | '/hotel'
    | '/partners'
    | '/program'
    | '/testimonials'
    | '/tourism'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRoute
  CompetitionRoute: typeof CompetitionRoute
  GalleryRoute: typeof GalleryRoute
  HotelRoute: typeof HotelRoute
  PartnersRoute: typeof PartnersRoute
  ProgramRoute: typeof ProgramRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TourismRoute: typeof TourismRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRoute,
  CompetitionRoute: CompetitionRoute,
  GalleryRoute: GalleryRoute,
  HotelRoute: HotelRoute,
  PartnersRoute: PartnersRoute,
  ProgramRoute: ProgramRoute,
  TestimonialsRoute: TestimonialsRoute,
  TourismRoute: TourismRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
